/**
 * Working out which calendar day a photographed page belongs to.
 *
 * Order of evidence, and why:
 *   1. The date written on the page. It is the only thing that is evidence
 *      *about the page itself*.
 *   2. The filename — but only when a person plausibly chose it. A camera or
 *      scanner puts the day you took the photo into the name, which for
 *      someone digitising an old journal is today, not the day they wrote it.
 *      A real incident: 50 pages named `IMG_20260925_xxxx.jpg` all resolved
 *      to one date and merged into a single entry.
 *   3. Nothing. Ask the person. Never infer a date from a neighbouring page.
 *
 * Every function here is pure and takes `today` explicitly so the behaviour
 * is testable rather than dependent on when the suite happens to run.
 */

export type DateSource = "page" | "filename";

export type DateFailure =
	/** Nothing usable on the page or in the filename. */
	| "none"
	/** The page names more than one date, so picking one would be a guess. */
	| "ambiguous-page"
	/** The filename holds more than one date. */
	| "ambiguous-filename";

export type DateResolution =
	| { date: string; source: DateSource; reason?: undefined }
	| { date: null; source?: undefined; reason: DateFailure };

/** Nothing before this is a plausible journal entry; it's a parsing accident. */
const EARLIEST_PLAUSIBLE_YEAR = 1900;

const MONTH_NAMES: Record<string, number> = {
	jan: 0,
	feb: 1,
	mar: 2,
	apr: 3,
	may: 4,
	jun: 5,
	jul: 6,
	aug: 7,
	sep: 8,
	oct: 9,
	nov: 10,
	dec: 11,
};

/**
 * True only for a date that exists. String-shaped checks aren't enough:
 * "2026-02-30" and "2023-02-29" are both well-formed and neither is a day.
 */
export function isRealCalendarDate(iso: string): boolean {
	const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
	if (!match) return false;
	const [, year, month, day] = match;
	const asDate = new Date(`${iso}T00:00:00Z`);
	return (
		asDate.getUTCFullYear() === Number(year) &&
		asDate.getUTCMonth() === Number(month) - 1 &&
		asDate.getUTCDate() === Number(day)
	);
}

/**
 * A real date that could actually be a journal entry: not in the future (you
 * can't have written it yet, and entry.save rejects it anyway), and not from
 * a century that means we parsed a serial number by accident.
 *
 * `today` is a local YYYY-MM-DD string; ISO dates compare correctly as strings.
 */
export function isPlausibleEntryDate(iso: string, today: string): boolean {
	if (!isRealCalendarDate(iso)) return false;
	if (Number(iso.slice(0, 4)) < EARLIEST_PLAUSIBLE_YEAR) return false;
	return iso <= today;
}

/**
 * Every YYYY-MM-DD / YYYYMMDD / YYYY_MM_DD in a string, in order.
 *
 * Deliberately refuses a match that sits inside a longer run of digits:
 * `ref1234202408120987` contains the characters of a date and means nothing.
 * The original version of this had no such boundary and matched it happily.
 * Purely numeric day-first or month-first orders (03-04-2024) are never
 * accepted anywhere here — they're genuinely ambiguous between locales, and
 * guessing silently is how pages end up filed under the wrong day.
 */
export function isoDatesIn(text: string): string[] {
	const found: string[] = [];
	const pattern = /(\d{4})[-_.]?(\d{2})[-_.]?(\d{2})/g;
	for (const match of text.matchAll(pattern)) {
		const start = match.index;
		const end = start + match[0].length;
		const before = start > 0 ? (text[start - 1] ?? "") : "";
		const after = text[end] ?? "";
		if (/\d/.test(before) || /\d/.test(after)) continue;
		found.push(`${match[1]}-${match[2]}-${match[3]}`);
	}
	return found;
}

/**
 * Names a camera, phone, scanner or messaging app generated by itself. Any
 * date inside one of these records when the file was created — never when the
 * page was written — so it must not be read as a journal date.
 */
const AUTO_GENERATED_NAME_PATTERNS: readonly RegExp[] = [
	/^img[\s_-]?\d/i, // IMG_1234, IMG-20260925-WA0001, IMG 0001
	/^mvimg/i, // Motion photos
	/^pxl[\s_-]?\d/i, // Pixel
	/^_?dsc[nf]?[\s_-]?\d/i, // DSC_0001, DSCN0001, DSCF1234, _DSC1234
	/^pict\d/i,
	/^p\d{7}/i, // P1000123
	/^gopr\d/i,
	/^screen[\s_-]?shot/i, // "Screenshot 2026-09-25 at 21.10.33"
	/^photo[\s_-]/i, // "Photo 25-09-2026, 21 10 33"
	/^scan[\s_-]?\d*$/i, // SCAN0001 — but not "Scan of Aug 12"
	/^scan[\s_-]+\d/i, // "Scan 2026-09-25"
	/^camscanner/i,
	/^signal[-_]/i,
	/^whatsapp/i,
	/wa\d{4}/i, // WhatsApp media suffix
	/^untitled/i,
	/^unnamed/i,
	/^image[\s_-]?\d*$/i,
	/^doc[\s_-]?\d/i,
	/^burst\d/i,
	/^\d{8}[\s_.-]\d{6}/, // 20260925_211033 — a capture timestamp
	/^\d{13,}$/, // epoch-millis filenames
];

export function looksAutoGenerated(filenameWithoutExtension: string): boolean {
	const name = filenameWithoutExtension.trim();
	return AUTO_GENERATED_NAME_PATTERNS.some((pattern) => pattern.test(name));
}

/**
 * Turns a casually written date ("Sep 3", "3 Sept", "September 3rd, 2024")
 * into YYYY-MM-DD. No year given means the most recent occurrence, never the
 * current year outright — "3 Sep" typed in January means last September.
 * Returns null for anything it isn't sure about, on purpose.
 */
export function parseCasualDate(raw: string, today: string): string | null {
	const trimmed = raw.trim();
	const monthFirst = trimmed.match(
		/^([A-Za-z]{3,9})\.?\s+(\d{1,2})(?:st|nd|rd|th)?(?:,?\s+(\d{4}))?$/,
	);
	const dayFirst = trimmed.match(
		/^(\d{1,2})(?:st|nd|rd|th)?\s+([A-Za-z]{3,9})\.?(?:,?\s+(\d{4}))?$/,
	);
	const match = monthFirst ?? dayFirst;
	if (!match) return null;

	const monthStr = monthFirst ? monthFirst[1] : dayFirst?.[2];
	const dayStr = monthFirst ? monthFirst[2] : dayFirst?.[1];
	const yearStr = monthFirst ? monthFirst[3] : dayFirst?.[3];
	if (!monthStr || !dayStr) return null;

	const month = MONTH_NAMES[monthStr.slice(0, 3).toLowerCase()];
	if (month === undefined) return null;
	const day = Number(dayStr);
	if (day < 1 || day > 31) return null;

	const toIso = (year: number) =>
		`${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;

	let year = yearStr ? Number(yearStr) : Number(today.slice(0, 4));
	if (!yearStr && toIso(year) > today) year -= 1;

	const iso = toIso(year);
	return isRealCalendarDate(iso) ? iso : null;
}

/**
 * The date a filename claims, if it was plausibly chosen by a person.
 */
export function filenameDate(filename: string, today: string): DateResolution {
	const base = filename.replace(/\.[^.]+$/, "").trim();
	if (looksAutoGenerated(base)) return { date: null, reason: "none" };

	const distinct = [
		...new Set(isoDatesIn(base).filter((d) => isPlausibleEntryDate(d, today))),
	];
	if (distinct.length > 1) return { date: null, reason: "ambiguous-filename" };
	// biome-ignore lint/style/noNonNullAssertion: length checked immediately above
	if (distinct.length === 1) return { date: distinct[0]!, source: "filename" };

	const casual = parseCasualDate(base.replace(/[-_]+/g, " "), today);
	if (casual && isPlausibleEntryDate(casual, today)) {
		return { date: casual, source: "filename" };
	}
	return { date: null, reason: "none" };
}

/**
 * The date the page itself is headed with, from dates the OCR step already
 * verified as real substrings of the transcription. More than one distinct
 * date means the page can't settle it and the person has to.
 */
export function pageDate(
	mentioned: readonly { resolvedDate: string }[],
	today: string,
): DateResolution {
	const distinct = [...new Set(mentioned.map((m) => m.resolvedDate))].filter(
		(d) => isPlausibleEntryDate(d, today),
	);

	if (distinct.length > 1) return { date: null, reason: "ambiguous-page" };
	// biome-ignore lint/style/noNonNullAssertion: length checked immediately above
	if (distinct.length === 1) return { date: distinct[0]!, source: "page" };
	return { date: null, reason: "none" };
}

/**
 * The page first, then the filename, then nobody — ask.
 *
 * A page carrying two dates still falls through to the filename: an explicit
 * name a person typed is better evidence than a page that contradicts itself.
 * Only if that fails too is the contradiction worth reporting back to them.
 */
export function resolveEntryDate(input: {
	mentionedDates: readonly { resolvedDate: string }[];
	filename: string;
	today: string;
}): DateResolution {
	const fromPage = pageDate(input.mentionedDates, input.today);
	if (fromPage.date) return fromPage;

	const fromFilename = filenameDate(input.filename, input.today);
	if (fromFilename.date) return fromFilename;

	if (fromPage.reason === "ambiguous-page") return fromPage;
	return fromFilename;
}

/**
 * Consecutive pages that share a date become one entry; a change of date
 * starts a new one. Order is the order the pages were added, which is the
 * order they were written in.
 *
 * Note that "consecutive" is evaluated over the list it's given. Undated
 * pages are held back and asked about separately, so two pages of the same
 * day with an undated page between them do end up in one entry — which is
 * right: same day, same entry.
 */
export function groupConsecutiveByDate<T extends { date: string }>(
	items: readonly T[],
): { date: string; items: T[] }[] {
	const groups: { date: string; items: T[] }[] = [];
	for (const item of items) {
		const current = groups.at(-1);
		if (current && current.date === item.date) current.items.push(item);
		else groups.push({ date: item.date, items: [item] });
	}
	return groups;
}
