import { describe, expect, it } from "vitest";

import {
	filenameDate,
	groupConsecutiveByDate,
	isoDatesIn,
	isPlausibleEntryDate,
	isRealCalendarDate,
	looksAutoGenerated,
	pageDate,
	parseCasualDate,
	resolveEntryDate,
} from "@/lib/entry-date";

/** Fixed so these tests mean the same thing whenever they run. */
const TODAY = "2026-09-25";

describe("isRealCalendarDate", () => {
	it("accepts real days, including a leap day in a leap year", () => {
		expect(isRealCalendarDate("2024-02-29")).toBe(true);
		expect(isRealCalendarDate("2026-01-01")).toBe(true);
		expect(isRealCalendarDate("2026-12-31")).toBe(true);
	});

	it("rejects days that don't exist", () => {
		expect(isRealCalendarDate("2023-02-29")).toBe(false); // not a leap year
		expect(isRealCalendarDate("2026-02-30")).toBe(false);
		expect(isRealCalendarDate("2026-04-31")).toBe(false);
		expect(isRealCalendarDate("2026-13-01")).toBe(false);
		expect(isRealCalendarDate("2026-00-10")).toBe(false);
		expect(isRealCalendarDate("2026-01-00")).toBe(false);
	});

	it("rejects anything that isn't exactly YYYY-MM-DD", () => {
		expect(isRealCalendarDate("2026-1-1")).toBe(false);
		expect(isRealCalendarDate("26-01-01")).toBe(false);
		expect(isRealCalendarDate("2026/01/01")).toBe(false);
		expect(isRealCalendarDate("")).toBe(false);
	});
});

describe("isPlausibleEntryDate", () => {
	it("accepts today and the past", () => {
		expect(isPlausibleEntryDate(TODAY, TODAY)).toBe(true);
		expect(isPlausibleEntryDate("2019-03-04", TODAY)).toBe(true);
	});

	it("rejects the future — you can't have written it yet", () => {
		expect(isPlausibleEntryDate("2026-09-26", TODAY)).toBe(false);
		expect(isPlausibleEntryDate("2031-01-01", TODAY)).toBe(false);
	});

	it("rejects dates so old they mean we parsed a serial number", () => {
		expect(isPlausibleEntryDate("1899-12-31", TODAY)).toBe(false);
		expect(isPlausibleEntryDate("1900-01-01", TODAY)).toBe(true);
	});
});

describe("isoDatesIn", () => {
	it("finds a date with any of the usual separators", () => {
		expect(isoDatesIn("2024-08-12")).toEqual(["2024-08-12"]);
		expect(isoDatesIn("2024_08_12")).toEqual(["2024-08-12"]);
		expect(isoDatesIn("2024.08.12")).toEqual(["2024-08-12"]);
		expect(isoDatesIn("20240812")).toEqual(["2024-08-12"]);
	});

	it("refuses a match buried inside a longer run of digits", () => {
		// The bug this whole module exists to prevent a repeat of: the old
		// regex had no boundary and happily read a date out of a serial number.
		expect(isoDatesIn("ref1234202408120987")).toEqual([]);
		expect(isoDatesIn("120240812")).toEqual([]);
		expect(isoDatesIn("202408121")).toEqual([]);
	});

	it("finds several, in order", () => {
		expect(isoDatesIn("2024-08-12 to 2024-08-14")).toEqual([
			"2024-08-12",
			"2024-08-14",
		]);
	});

	it("returns nothing when there's nothing to find", () => {
		expect(isoDatesIn("holiday photos")).toEqual([]);
		expect(isoDatesIn("")).toEqual([]);
	});
});

describe("looksAutoGenerated", () => {
	const generated = [
		"IMG_20260925_0001",
		"IMG-20260925-WA0001",
		"IMG 0001",
		"IMG_1234",
		"MVIMG_20260925",
		"PXL_20260925_182233123",
		"DSC_0001",
		"DSCN0001",
		"DSCF1234",
		"_DSC1234",
		"PICT0001",
		"P1000123",
		"GOPR0042",
		"Screenshot 2026-09-25 at 21.10.33",
		"Screen Shot 2026-09-25 at 21.10.33",
		"Photo 25-09-2026, 21 10 33",
		"Scan 2026-09-25",
		"SCAN0001",
		"CamScanner 09-25-2026 21.10",
		"Signal-2026-09-25-211033",
		"WhatsApp Image 2026-09-25 at 21.10.33",
		"20260925_211033",
		"1758830000000",
		"untitled",
		"unnamed",
		"image",
		"image_3",
		"DOC_0012",
		"BURST0001",
	];
	for (const name of generated) {
		it(`flags "${name}" as camera or app generated`, () => {
			expect(looksAutoGenerated(name)).toBe(true);
		});
	}

	const deliberate = [
		"2024-08-12",
		"12 Aug 2024",
		"Aug 12 2024",
		"journal 2024-08-12",
		"Scan of Aug 12 2024",
		"holiday",
	];
	for (const name of deliberate) {
		it(`leaves "${name}" alone`, () => {
			expect(looksAutoGenerated(name)).toBe(false);
		});
	}
});

describe("parseCasualDate", () => {
	it("reads the formats a person actually types", () => {
		expect(parseCasualDate("2 Sep 2024", TODAY)).toBe("2024-09-02");
		expect(parseCasualDate("Sep 2 2024", TODAY)).toBe("2024-09-02");
		expect(parseCasualDate("September 2nd, 2024", TODAY)).toBe("2024-09-02");
		expect(parseCasualDate("2nd September 2024", TODAY)).toBe("2024-09-02");
		expect(parseCasualDate("12 August 2024", TODAY)).toBe("2024-08-12");
	});

	it("with no year, takes the most recent occurrence rather than this year", () => {
		// Today is 25 Sep 2026, so "3 Sep" is this year and "3 Oct" is last.
		expect(parseCasualDate("3 Sep", TODAY)).toBe("2026-09-03");
		expect(parseCasualDate("3 Oct", TODAY)).toBe("2025-10-03");
	});

	it("rejects what it can't be sure of", () => {
		expect(parseCasualDate("Someday", TODAY)).toBeNull();
		expect(parseCasualDate("Smarch 3 2024", TODAY)).toBeNull();
		expect(parseCasualDate("31 Feb 2024", TODAY)).toBeNull();
		expect(parseCasualDate("32 Aug 2024", TODAY)).toBeNull();
		expect(parseCasualDate("", TODAY)).toBeNull();
	});
});

describe("filenameDate", () => {
	it("ignores the capture date a camera puts in the name", () => {
		// The exact production incident: 50 pages photographed in one sitting,
		// every filename carrying that day, all merged into a single entry.
		expect(filenameDate("IMG_20260925_0001.jpg", TODAY)).toEqual({
			date: null,
			reason: "none",
		});
		expect(filenameDate("PXL_20260925_182233123.jpg", TODAY)).toEqual({
			date: null,
			reason: "none",
		});
		expect(
			filenameDate("Screenshot 2026-09-25 at 21.10.33.png", TODAY),
		).toEqual({ date: null, reason: "none" });
		expect(
			filenameDate("WhatsApp Image 2026-09-25 at 21.10.33.jpeg", TODAY),
		).toEqual({ date: null, reason: "none" });
	});

	it("trusts a name a person chose", () => {
		expect(filenameDate("2024-08-12.jpg", TODAY)).toEqual({
			date: "2024-08-12",
			source: "filename",
		});
		expect(filenameDate("20240812.png", TODAY)).toEqual({
			date: "2024-08-12",
			source: "filename",
		});
		expect(filenameDate("12 Aug 2024.jpeg", TODAY)).toEqual({
			date: "2024-08-12",
			source: "filename",
		});
		expect(filenameDate("2024_08_12.HEIC", TODAY)).toEqual({
			date: "2024-08-12",
			source: "filename",
		});
	});

	it("asks rather than picking one of two dates", () => {
		expect(filenameDate("2024-08-12 to 2024-08-14.jpg", TODAY)).toEqual({
			date: null,
			reason: "ambiguous-filename",
		});
	});

	it("is fine with the same date written twice", () => {
		expect(filenameDate("2024-08-12 (2024-08-12).jpg", TODAY)).toEqual({
			date: "2024-08-12",
			source: "filename",
		});
	});

	it("refuses impossible, future and ancient dates", () => {
		expect(filenameDate("2024-02-30.jpg", TODAY).date).toBeNull();
		expect(filenameDate("2031-01-01.jpg", TODAY).date).toBeNull();
		expect(filenameDate("1899-01-01.jpg", TODAY).date).toBeNull();
	});

	it("finds nothing in a name that has nothing", () => {
		expect(filenameDate("vacation_photo_final.jpg", TODAY)).toEqual({
			date: null,
			reason: "none",
		});
		expect(filenameDate("page 3.jpg", TODAY).date).toBeNull();
	});

	it("handles names with no extension or several dots", () => {
		expect(filenameDate("2024-08-12", TODAY).date).toBe("2024-08-12");
		expect(filenameDate("journal.2024-08-12.jpg", TODAY).date).toBe(
			"2024-08-12",
		);
	});
});

describe("pageDate", () => {
	it("uses the one date the page is headed with", () => {
		expect(pageDate([{ resolvedDate: "2024-08-12" }], TODAY)).toEqual({
			date: "2024-08-12",
			source: "page",
		});
	});

	it("treats the same date mentioned twice as one date", () => {
		expect(
			pageDate(
				[{ resolvedDate: "2024-08-12" }, { resolvedDate: "2024-08-12" }],
				TODAY,
			),
		).toEqual({ date: "2024-08-12", source: "page" });
	});

	it("won't choose between two different dates on one page", () => {
		expect(
			pageDate(
				[{ resolvedDate: "2024-08-12" }, { resolvedDate: "2024-08-14" }],
				TODAY,
			),
		).toEqual({ date: null, reason: "ambiguous-page" });
	});

	it("drops a future date instead of trusting it", () => {
		expect(pageDate([{ resolvedDate: "2031-05-05" }], TODAY)).toEqual({
			date: null,
			reason: "none",
		});
		// One real date and one impossible one leaves exactly one real date.
		expect(
			pageDate(
				[{ resolvedDate: "2024-08-12" }, { resolvedDate: "2031-05-05" }],
				TODAY,
			),
		).toEqual({ date: "2024-08-12", source: "page" });
	});

	it("reports nothing found for a page with no dates", () => {
		expect(pageDate([], TODAY)).toEqual({ date: null, reason: "none" });
	});
});

describe("resolveEntryDate", () => {
	it("prefers the page over the filename when they disagree", () => {
		expect(
			resolveEntryDate({
				mentionedDates: [{ resolvedDate: "2024-08-12" }],
				filename: "2026-01-01.jpg",
				today: TODAY,
			}),
		).toEqual({ date: "2024-08-12", source: "page" });
	});

	it("solves the incident: a dated page inside a camera-named file", () => {
		expect(
			resolveEntryDate({
				mentionedDates: [{ resolvedDate: "2019-04-03" }],
				filename: "IMG_20260925_0001.jpg",
				today: TODAY,
			}),
		).toEqual({ date: "2019-04-03", source: "page" });
	});

	it("falls back to a deliberate filename when the page has no date", () => {
		expect(
			resolveEntryDate({
				mentionedDates: [],
				filename: "2024-08-12.jpg",
				today: TODAY,
			}),
		).toEqual({ date: "2024-08-12", source: "filename" });
	});

	it("uses an explicit filename when the page contradicts itself", () => {
		expect(
			resolveEntryDate({
				mentionedDates: [
					{ resolvedDate: "2024-08-12" },
					{ resolvedDate: "2024-08-14" },
				],
				filename: "2024-08-12.jpg",
				today: TODAY,
			}),
		).toEqual({ date: "2024-08-12", source: "filename" });
	});

	it("reports the page's contradiction when the filename can't settle it", () => {
		expect(
			resolveEntryDate({
				mentionedDates: [
					{ resolvedDate: "2024-08-12" },
					{ resolvedDate: "2024-08-14" },
				],
				filename: "IMG_0001.jpg",
				today: TODAY,
			}),
		).toEqual({ date: null, reason: "ambiguous-page" });
	});

	it("gives up honestly on an undated page in a camera-named file", () => {
		expect(
			resolveEntryDate({
				mentionedDates: [],
				filename: "IMG_20260925_0002.jpg",
				today: TODAY,
			}),
		).toEqual({ date: null, reason: "none" });
	});

	it("never returns a date it wasn't given — no inference from neighbours", () => {
		const result = resolveEntryDate({
			mentionedDates: [],
			filename: "IMG_20260925_0003.jpg",
			today: TODAY,
		});
		expect(result.date).toBeNull();
	});
});

describe("groupConsecutiveByDate", () => {
	const page = (date: string, text: string) => ({ date, text });

	it("returns nothing for no pages", () => {
		expect(groupConsecutiveByDate([])).toEqual([]);
	});

	it("keeps consecutive pages of one day together", () => {
		const pages = [
			page("2024-08-12", "one"),
			page("2024-08-12", "two"),
			page("2024-08-13", "three"),
		];
		expect(groupConsecutiveByDate(pages)).toEqual([
			{ date: "2024-08-12", items: [pages[0], pages[1]] },
			{ date: "2024-08-13", items: [pages[2]] },
		]);
	});

	it("starts a new entry every time the date changes back and forth", () => {
		const pages = [
			page("2024-08-12", "a"),
			page("2024-08-13", "b"),
			page("2024-08-12", "c"),
		];
		expect(groupConsecutiveByDate(pages).map((g) => g.date)).toEqual([
			"2024-08-12",
			"2024-08-13",
			"2024-08-12",
		]);
	});

	it("merges 50 pages into one day only when they really share a date", () => {
		// The shape of the production incident, now only reachable when the
		// pages genuinely carry the same date rather than the same filename.
		const fifty = Array.from({ length: 50 }, (_, i) =>
			page("2024-08-12", `page ${i}`),
		);
		const groups = groupConsecutiveByDate(fifty);
		expect(groups).toHaveLength(1);
		expect(groups[0]?.items).toHaveLength(50);
	});

	it("gives 50 pages of 50 different days 50 entries", () => {
		const fifty = Array.from({ length: 50 }, (_, i) =>
			page(`2024-08-${String(i + 1).padStart(2, "0")}`, `page ${i}`),
		);
		expect(groupConsecutiveByDate(fifty)).toHaveLength(50);
	});
});
