CREATE TABLE "user_consent" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_consent_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"termsVersion" text NOT NULL,
	"consentedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE INDEX "user_consent_user_id_idx" ON "user_consent" USING btree ("userId");